language: node_js
node_js:
  - "8"
  - "9"

os: [linux]
dist: trusty
sudo: required
cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install

script:
- yarn test
- yarn build

deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  message: "Travis CI Deploy $TRAVIS_COMMIT (Build $TRAVIS_BUILD_NUMBER)"
  on:
    branch: master
